### ISSUE TITLE
Eviction can crash by evicting more data than present on a device

### ISSUE THREAD

**Issue by wlruys** [wlruys/task4feedback#4]
Case: 4GB blocks, 5 x 5 block cholesky graph. 

```
Notice: Logging enabled
Scheduler Architecture: <class 'task4feedback.simulator.schedulers.parla.architecture.ParlaArchitecture'>
Scheduler State: <class 'task4feedback.simulator.schedulers.parla.state.ParlaState'>
Initial Task Order: [POTRF[0], SOLVE[1, 0], SOLVE[5, 0], SYRK[1, 0], POTRF[1], SOLVE[2, 0], SOLVE[4, 0], SOLVE[3, 0], GEMM[4, 1, 0], GEMM[5, 1, 0], GEMM[4, 2, 
0], SOLVE[5, 1], GEMM[4, 3, 0], GEMM[5, 2, 0], SYRK[4, 0], GEMM[5, 3, 0], GEMM[3, 1, 0], SYRK[2, 0], GEMM[2, 1, 0], SYRK[5, 0], GEMM[3, 2, 0], GEMM[5, 4, 0], 
SYRK[5, 1], SOLVE[3, 1], SYRK[3, 0], SOLVE[4, 1], SYRK[4, 1], GEMM[5, 3, 1], GEMM[4, 3, 1], SYRK[3, 1], GEMM[5, 4, 1], SOLVE[2, 1], GEMM[3, 2, 1], GEMM[5, 2, 
1], SYRK[2, 1], GEMM[4, 2, 1], POTRF[2], SOLVE[3, 2], SOLVE[5, 2], SOLVE[4, 2], SYRK[3, 2], POTRF[3], GEMM[5, 3, 2], SOLVE[5, 3], SYRK[5, 2], SYRK[5, 3], 
SYRK[4, 2], GEMM[5, 4, 2], GEMM[4, 3, 2], SOLVE[4, 3], GEMM[5, 4, 3], SYRK[4, 3], POTRF[4], SOLVE[5, 4], SYRK[5, 4], POTRF[5]]
Traceback (most recent call last):
  File "/home/wlruys/syncthing/workspace/parladev/task4feedback/test/graphs/test_cholesky.py", line 106, in <module>
    test_data()
  File "/home/wlruys/syncthing/workspace/parladev/task4feedback/test/graphs/test_cholesky.py", line 62, in test_data
    simulated_time = simulator.run()
                     ^^^^^^^^^^^^^^^
  File "/home/wlruys/syncthing/workspace/parladev/task4feedback/src/task4feedback/simulator/simulator.py", line 131, in run
    new_events = self.process_event(event)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wlruys/syncthing/workspace/parladev/task4feedback/src/task4feedback/simulator/simulator.py", line 103, in process_event
    new_event_pairs = self.mechanisms[event](self.state)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wlruys/syncthing/workspace/parladev/task4feedback/src/task4feedback/simulator/schedulers/architecture.py", line 41, in wrapper
    return function(scheduler_state, event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wlruys/syncthing/workspace/parladev/task4feedback/src/task4feedback/simulator/schedulers/parla/architecture.py", line 651, in complete_task
    complete_task(task, scheduler_state)
  File "/home/wlruys/syncthing/workspace/parladev/task4feedback/src/task4feedback/simulator/schedulers/parla/architecture.py", line 255, in complete_task
    scheduler_state.release_data(phase, task, verbose=verbose)
  File "/home/wlruys/syncthing/workspace/parladev/task4feedback/src/task4feedback/simulator/schedulers/parla/state.py", line 969, in release_data
    _finish_evict(self, task.read_accesses, task, AccessType.EVICT)
  File "/home/wlruys/syncthing/workspace/parladev/task4feedback/src/task4feedback/simulator/schedulers/parla/state.py", line 798, in _finish_evict
    state.resource_pool.remove_device_resources(
  File "/home/wlruys/syncthing/workspace/parladev/task4feedback/src/task4feedback/simulator/resources.py", line 85, in remove_device_resources
    resource_set.verify()
  File "/home/wlruys/syncthing/workspace/parladev/task4feedback/src/task4feedback/simulator/resourceset.py", line 82, in verify
    raise ValueError(f"ResourceSet {self} contains negative value.")
ValueError: ResourceSet ResourceSet(vcus=0, memory=-4294967296, copy=0) contains negative value.
```

**Comment by wlruys** [comment]
I'm fairly certain I resolved this a while ago, and that it was due to an incorrect relative ordering of planned data movement and data eviction events.
