### ISSUE TITLE
execution failure due to data invalid

### ISSUE THREAD

**Issue by nicelhc13** [wlruys/task4feedback#9]
Target application: test_stencil.py
Branch: rl_state
Command line:
`python test_stencil.py -e 1 -m eft_with_data  -ln  -o random -g 4 -pb 10 -dd 0.5  -lo  -d 'rr'`
 
Error stack:
```
Traceback (most recent call last):
  File "/net/ohm/export/cdgc/hlee/workspace/rl/task4feedback/scripts/rl_plotting/test_stencil.py", line 371, in <module>
    test_data()
  File "/net/ohm/export/cdgc/hlee/workspace/rl/task4feedback/scripts/rl_plotting/test_stencil.py", line 285, in test_data
    simulated_time, task_order_log, success = simulator.run()
                                              ^^^^^^^^^^^^^^^
  File "/net/ohm/export/iss/hlee/miniconda3/envs/rl/lib/python3.12/site-packages/task4feedback/simulator/simulator.py", line 269, in run
    new_events = self.process_event(event)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/ohm/export/iss/hlee/miniconda3/envs/rl/lib/python3.12/site-packages/task4feedback/simulator/simulator.py", line 233, in process_event
    new_event_pairs = self.mechanisms[event](
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/ohm/export/iss/hlee/miniconda3/envs/rl/lib/python3.12/site-packages/task4feedback/simulator/schedulers/architecture.py", line 51, in wrapper
    return function(scheduler_state, event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/ohm/export/iss/hlee/miniconda3/envs/rl/lib/python3.12/site-packages/task4feedback/simulator/schedulers/parla/architecture.py", line 932, in complete_task
    complete_task(task, scheduler_state)
  File "/net/ohm/export/iss/hlee/miniconda3/envs/rl/lib/python3.12/site-packages/task4feedback/simulator/schedulers/parla/architecture.py", line 410, in complete_task
    scheduler_state.release_data(phase, task, verbose=verbose)
  File "/net/ohm/export/iss/hlee/miniconda3/envs/rl/lib/python3.12/site-packages/task4feedback/simulator/schedulers/parla/state.py", line 1369, in release_data
    _finish_move(self, task.read_accesses, task)
  File "/net/ohm/export/iss/hlee/miniconda3/envs/rl/lib/python3.12/site-packages/task4feedback/simulator/schedulers/parla/state.py", line 1000, in _finish_move
    prior_state = data.finish_move(
                  ^^^^^^^^^^^^^^^^^
  File "/net/ohm/export/iss/hlee/miniconda3/envs/rl/lib/python3.12/site-packages/task4feedback/simulator/data.py", line 969, in finish_move
    return self.status.finish_move(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/ohm/export/iss/hlee/miniconda3/envs/rl/lib/python3.12/site-packages/task4feedback/simulator/data.py", line 811, in finish_move
    raise RuntimeError(
RuntimeError: Task T[2, 8, 4].data[1, 1, 0, 7, 4] cannot move data (1, 1, 0, 7, 4) from a device that is not valid.
(rl) hlee@tuxedo ~/hlee/workspace/rl/task4feedback/scripts/rl_plotting (rl-state) $ python test_stencil.py -e 1 -m eft_with_data  -ln  -o random -g 4 -pb 10 -dd 0.5  -lo  -d 'rr'  > log^C
```

Change the attached file to replay.noise and replay.order, put them on the same folder, and run the script to reproduce the error.

[replay.noise.txt](https://github.com/wlruys/task4feedback/files/15444954/replay.noise.txt)
[replay.order.txt](https://github.com/wlruys/task4feedback/files/15444955/replay.order.txt)

**Comment by nicelhc13** [comment]
I got more detailed information.
I tracked 1,1,0,7,4 data.
```
Task T[2, 8, 4].data[1, 1, 0, 7, 4], start:58197.831, end:58251.518, device:GPU[0]
Task T[2, 6, 6]_eviction_3[1, 1, 0, 7, 4], start:58197.833, end:58197.833, device:GPU[3]
...
Task T[2, 8, 4].data[1, 1, 0, 7, 4] moves data (1, 1, 0, 7, 4) from a device GPU[3] to GPU[0] <-- this is failed point.
```
So as you can see, 1,1,0,7,4 is moved to GPU0, and right after that, its instance on GPU3 is evicted.
Later, the task, 2,8,4, thinks that it is still on GPU3 and tries to move from there, which is a bug.

**Comment by nicelhc13** [comment]
issue was b/c of the following case:

eviction task was created without dependency
data task was created and made dependency with the eviction task.
both of them are in the ready queue.
so the dependency between eviction and data tasks do not enforce the correct ordering and runs in parallel.

https://github.com/wlruys/task4feedback/commit/5e0896b8924e7a186a175513c0deba85b8e719d6

this fixed the issue.
